spring.application.name=costcompass
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=costcompass
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.ai.openai.chat.options.model=gpt-4o-mini

spring.datasource.url=jdbc:postgresql://localhost:5432/costcompass_ai_memory
spring.datasource.username=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
